RENDER_UTIL_DIR:= ../../render_util
SHADER_DIR:= $(RENDER_UTIL_DIR)/shaders
ENGINE_BASE_BUILD_DIR:= $(RENDER_UTIL_DIR)/build/$(PLATFORM)
VIEWER_BUILD_DIR:= $(ENGINE_BASE_BUILD_DIR)/viewer
ENGINE_BUILD_DIR:= $(ENGINE_BASE_BUILD_DIR)/render_util
GL_WRAPPER_BUILD_DIR:= $(ENGINE_BASE_BUILD_DIR)/gl_wrapper
